spring:
  application:
    name: cloud-oms
  profiles:
    active: dev

  cloud:
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID}
        tenant-id: ${AZURE_TENANT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}

      keyvault:
        secret:
          property-sources:
            - endpoint: https://cloud-oms-dev.vault.azure.net/

  datasource:
    url: ${cloud-oms-db-url}
    username: ${cloud-oms-db-username}
    password: ${cloud-oms-db-password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Default settings (common to all profiles)
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  health:
    db:
      enabled: true
    diskspace:
      enabled: true