spring:
  application:
    name: cloud-oms
  profiles:
    active: dev
  workflow:
    enabled: true

# Default settings (common to all profiles)
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  health:
    db:
      enabled: true
    diskspace:
      enabled: true