spring:
  datasource:
    url: ${cloud-oms-db-url}
    username: ${cloud-oms-db-username}
    password: ${cloud-oms-db-password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    azure:
      keyvault:
        secret:
          enabled: true
          property-sources:
            - endpoint: https://cloud-oms-dev.vault.azure.net/      
 