spring:
  application:
    name: cloud-oms

# Default settings (common to all profiles)
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
