spring:
  datasource:
    url: ${cloud-oms-db-url}
    username: ${cloud-oms-db-username}
    password: ${cloud-oms-db-password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID}
        tenant-id: ${AZURE_TENANT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: https://cloud-oms-dev.vault.azure.net/      
 
